ismywebsiteinsecure.sh

diff --git a/vulnerabilitiesTestGuide b/vulnerabilitiesTestGuide
--- a/vulnerabilitiesTestGuide
+++ b/vulnerabilitiesTestGuide
@@ -1,6 +1,52 @@
 # Note: Perform these tests only on websites and web platforms for which you have explicit authorization. Unauthorized testing is illegal and unethical.
 # Note: Most of these tools are available in Kali Linux.
 
+#!/bin/bash
+
+# Function to validate URL format
+validate_url() {
+    if [[ ! $1 =~ ^(http|https):// ]]; then
+        echo "Error: The provided parameter is not a valid URL. It should start with http:// or https://."
+        exit 1
+    fi
+}
+
+
+# Check if the required tools are installed
+required_tools=(whois dnsrecon whatweb nc wpscan sqlmap curl nmap sslscan nrich dig)
+for tool in "${required_tools[@]}"; do
+    if ! command -v $tool &> /dev/null; then
+        echo "$tool is not installed. Please install it before running the script."
+        exit 1
+    fi
+done
+
+# Check if a URL parameter is provided
+if [ "$#" -ne 1 ]; then
+    echo "Usage: $0 <url>"
+    exit 1
+fi
+
+# Get the URL from the first argument
+url="$1"
+
+# Validate the URL format
+validate_url "$url"
+
+# Extract host and domain
+host=$(echo "$url" | awk -F[/:] '{print $4}')
+domain=$(echo "$host" | awk -F. '{if (NF>2) {print $(NF-1)"."$NF} else {print $0}}')
+# Get the first IPv4 address from DNS
+ipv4=$(dig +short "$host" | tail -n1)
+
+echo
+echo Host=$host
+echo Domain=$domain
+echo IPv4=$ipv4
+echo Url=$url
+echo
+
+
 # WHOIS lookup for domain information
 whois <domain>
 
@@ -10,8 +56,8 @@ dnsrecon -d <domain>
 # Identify technologies used on the website
 whatweb <url>
 
-# Check MySQL or MariaDB database version
-nc <host> 3306
+# Check MSSQL, MySQL or MariaDB database version
+nmap -p 1433,3306 --script ms-sql-info,mysql-info <host>
 
 # Wordpress vulnerability scan
 wpscan --stealthy --url <url>
@@ -58,19 +104,6 @@ sudo nmap -sV -sC --script vuln* -O -p <port1,port2,...> <host>
 # Shodan scan
 echo <IPv4> | nrich -
 
-# Lighthouse for performance and security insights
-chrome Browser > developer tools > lighthouse
-
-# Web vulnerability scanners
-OWASP ZAP https://www.zaproxy.org/
-Burp Suite https://portswigger.net/burp/pro/
-
-# Host vulnerability scanners
-Tenable Nessus https://www.tenable.com/products/nessus
-Greenbone OpenVAS https://openvas.org/
-
-# Test for vulnerabilities and configuration errors
-isMyWebsiteInsecure.bat
 
 
 
